// app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import { LoginProvider } from "./context/LoginContext";

export const metadata: Metadata = {
  title: "User Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <LoginProvider >
          <NavBar />
          {children} 
      </LoginProvider>
      </body>
    </html>
  );
}
